import { notificationService } from '@/utils/notificationService';

export type NotificationCategory = 'chat' | 'task' | 'lead' | 'activity' | 'project' | 'system';

export interface WorkspaceNotificationEvent {
  id: string;
  category: NotificationCategory;
  title: string;
  body: string;
  actorId?: string;
  actorName?: string;
  targetUrl?: string;
  soundType?: 'notification' | 'success' | 'alert';
  createdAt?: string;
}

const recentNotificationIds = new Set<string>();

export const workspaceNotificationService = {
  /**
   * Process and dispatch a workspace notification.
   * Suppresses notifications if triggered by the logged-in user or if duplicate.
   */
  notify(event: WorkspaceNotificationEvent, currentUserId?: string) {
    if (!event || !event.id) return;

    // Suppress notifications generated by self
    if (event.actorId && currentUserId && event.actorId === currentUserId) {
      return;
    }

    // Suppress duplicate events within session
    if (recentNotificationIds.has(event.id)) {
      return;
    }

    recentNotificationIds.add(event.id);
    if (recentNotificationIds.size > 100) {
      const firstKey = recentNotificationIds.values().next().value;
      if (firstKey) recentNotificationIds.delete(firstKey);
    }

    const sound = event.soundType || (event.category === 'chat' ? 'notification' : event.category === 'task' ? 'alert' : 'success');
    notificationService.playSound(sound);

    // Desktop/Mobile Push Notification
    notificationService.showNotification(event.title, {
      body: event.body,
      tag: `workspace-${event.category}-${event.id}`,
      requireInteraction: event.category === 'task' || event.category === 'lead',
      data: { url: event.targetUrl || '/' }
    });

    // Broadcast in-app event for UI components/toasts
    window.dispatchEvent(new CustomEvent('workspace-notification-received', { detail: event }));
  },

  formatPayload(table: string, eventType: string, record: any, user: any): WorkspaceNotificationEvent | null {
    if (!record || !user) return null;
    const currentUserId = typeof user === 'string' ? user : user.id;
    const userRole = typeof user === 'object' ? user.role : 'user';
    const id = record.id || Math.random().toString(36).substring(2, 9);
    const nowStr = new Date().toISOString();

    if (table === 'chat_messages') {
      // Chat: Notify everyone except the sender
      if (record.user_id === currentUserId) return null;
      const senderName = record.users?.username || record.users?.full_name || 'Teammate';
      return {
        id,
        category: 'chat',
        title: `💬 New Message from ${senderName}`,
        body: record.message || 'Sent a message in Workspace Chat',
        actorId: record.user_id,
        actorName: senderName,
        targetUrl: '/?open_chat=true',
        soundType: 'notification',
        createdAt: record.created_at || nowStr
      };
    }

    if (table === 'crm_tasks') {
      const taskTitle = record.title || 'New Task';
      if (eventType === 'INSERT') {
        // STRICT TARGETING: Only notify the assignee
        if (record.assigned_to !== currentUserId) return null;
        
        return {
          id,
          category: 'task',
          title: `📋 New Task Assigned to You!`,
          body: `${taskTitle} (Priority: ${record.priority || 'Medium'})`,
          actorId: record.created_by,
          targetUrl: '/crm/tasks',
          soundType: 'alert',
          createdAt: record.created_at || nowStr
        };
      } else if (eventType === 'UPDATE' && record.status === 'Completed') {
        // STRICT TARGETING: When a task is completed, notify the creator (if it wasn't the creator who completed it)
        if (record.created_by !== currentUserId) return null;
        
        return {
          id: `${id}-completed`,
          category: 'task',
          title: `✅ Task Completed!`,
          body: `"${taskTitle}" has been marked as completed.`,
          actorId: record.assigned_to,
          targetUrl: '/crm/tasks',
          soundType: 'success',
          createdAt: nowStr
        };
      }
    }

    if (table === 'crm_leads') {
      const company = record.company_name || record.contact_person || 'New Lead';
      if (eventType === 'INSERT') {
        // STRICT TARGETING: Notify Assignee. If unassigned, notify Admins to assign it.
        const isAssignee = record.assigned_to === currentUserId;
        const isAdmin = userRole === 'admin';
        
        if (!isAssignee && !isAdmin) return null;

        return {
          id,
          category: 'lead',
          title: isAssignee ? `💼 New Lead Assigned to You` : `💼 New CRM Lead Added`,
          body: `${company} added to sales pipeline (${record.stage || 'New Leads'})`,
          actorId: record.created_by,
          targetUrl: '/crm/leads',
          soundType: 'success',
          createdAt: record.created_at || nowStr
        };
      } else if (eventType === 'UPDATE' && record.stage) {
        // STRICT TARGETING: Only notify the assignee or the creator when a lead changes stages
        if (record.assigned_to !== currentUserId && record.created_by !== currentUserId) return null;

        return {
          id: `${id}-stage-${record.stage}`,
          category: 'lead',
          title: `🚀 Lead Stage Moved`,
          body: `${company} moved to "${record.stage}"`,
          actorId: record.assigned_to, // the person who likely moved it
          targetUrl: '/crm/pipeline',
          soundType: 'notification',
          createdAt: nowStr
        };
      }
    }

    if (table === 'projects') {
      if (eventType === 'INSERT') {
        // For now, projects are broadcasted, but we could restrict it to project_members table
        return {
          id,
          category: 'project',
          title: `📁 New Project Created`,
          body: record.name || 'New workspace project created',
          actorId: record.created_by,
          targetUrl: `/project/${record.id}`,
          soundType: 'success',
          createdAt: record.created_at || nowStr
        };
      }
    }

    return null;
  }
};
